min-first-active-gen = 0
max-first-active-gen = 70
min-active-window-gens = 0
max-active-window-gens = 70
min-stable-interval = 15

max-stable-pop = 100
max-active-cells = 100

stabilise-results = true

pattern = '''
x = 22, y = 21, rule = LifeHistory
.A$2.A$3A$5.A$6.A$4.3A$9.A$10.A$8.3A$13.A$14.A$12.3A3$15.7B$15.7B$15.
7B$15.7B$15.7B$15.7B$15.7B!
'''
