first-active-range = [3, 7]
active-window-range = [3, 40]
min-stable-interval = 5

ever-active-bounds = [5, 5]

stabilise-results = true
skip-glancing = true
forbid-eater2 = false

pattern-center = [15, 10]
pattern = '''
x = 29, y = 24, rule = LifeHistory
11.18B$7.A3.18B$8.A2.18B$6.3A2.18B$11.18B$11.18B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B!
'''
