min-first-active-gen = 0
max-first-active-gen = 80
min-active-window-gens = 4
max-active-window-gens = 30
min-stable-interval = 4

max-active-cells = 16
ever-active-bounds = [6, 6]

# max-changed-cells = 7
# max-changed-cells-grace-period = 3

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [10, 20]
pattern = '''
x = 27, y = 42, rule = LifeHistory
22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$
22B$22B$22B$22B$22B$22B4.A$22B2.A.A$22B2.3A$22B2.A$22B$22B$22B$22B$
22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B!
'''
