first-active-range = [1, 40]
active-window-range = [0, 20]
min-stable-interval = 10

max-active-cells = 8

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

# debug = true

pattern-center = [15, 15]
pattern = '''
x = 27, y = 33, rule = LifeHistory
27B$27B$27B$27B$27B$27B$27B$27B$27B$27B$27B$27B$27B$6.21B$6.21B$2A4.
21B$.A4.21B$.2A3.21B$2.2A2.21B$6.21B$6.21B$6.21B$6.21B$6.21B$6.21B$6.
21B$6.21B$6.21B$6.21B$6.21B$6.21B$6.21B$6.21B!
'''
