# Snarks are easy to find if you know exactly where to look

min-first-active-gen = 40
max-first-active-gen = 42
min-active-window-gens = 0
max-active-window-gens = 20

max-active-cells = 15
ever-active-bounds = [6, 4]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 32, y = 27, rule = LifeHistory
19.A$9.A7.3A$7.A.A6.A14.B$8.2A6.2A12.2B$29.3B$28.4B$27.5B$26.6B$25.7B
$24.8B$6.2A15.9B$5.A.A5.2A.16B$5.A7.2A.16B$4.2A10.16B$8.24B$8.24B$32B
$32B$32B$32B$32B$32B$32B$32B$32B$32B$32B!
'''

# #F 46 19 10
# .....
# .***.
# ...*.
# ..*..
# .....
