first-active-range = [0, 4]
active-window-range = [0, 30]
min-stable-interval = 5

max-active-cells = 6

stabilise-results = true
minimise-results = true

pattern = '''
x = 19, y = 15, rule = LifeHistory
5.A$6.A$4.3A3$19B$19B$19B$19B$19B$19B$19B$19B$19B$19B!
'''
