min-first-active-gen = 0
max-first-active-gen = 20
min-stable-interval = 5

max-active-window-gens = 20

max-pre-interaction-choices = 4
max-post-interaction-choices = 40
max-stable-pop = 100

max-active-cells = 8

stabilise-results = true
skip-glancing = true
forbid-blocks = true

# debug = true

pattern = '''
x = 19, y = 15, rule = LifeHistory
5.A$6.A$4.3A3$19B$19B$19B$19B$19B$19B$19B$19B$19B$19B!
'''
