first-active-range = [0, 10]
min-stable-interval = 5

max-active-window-gens = 20

max-stable-pop = 100
max-active-cells = 8

stabilise-results = false
forbid-blocks = true

pattern = '''
x = 19, y = 15, rule = LifeHistory
5.A$6.A$4.3A3$19B$19B$19B$19B$19B$19B$19B$19B$19B$19B!
'''
