first-active-range = [0, 10]
active-window-range = [0, 30]
min-stable-interval = 4

max-active-cells = 10

stabilise-results = true

pattern-center = [14, 14]
pattern = '''
x = 28, y = 28, rule = LifeHistory
10B$10B$10B$10B$10B.A3.A$10B2.3A$10B$28B$28B$28B$28B$28B$28B$28B$28B$
28B$28B$28B$28B$28B$28B$28B$28B$28B$28B$28B$28B$28B!
'''
