first-active-range = [1, 65]
active-window-range = [0, 20]
min-stable-interval = 4

max-active-cells = 17
ever-active-bounds = [7, 7]

stabilise-results = true

pattern-center = [15, 15]
pattern = '''
x = 30, y = 33, rule = LifeHistory
30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$
30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$30B$12B6.12B$12B2.3A.12B$12B.
A2.A.12B$12B.A.A2.12B$12B2.A3.12B!
'''
