first-active-range = [30, 50]
active-window-range = [0, 20]

max-active-cells = 20
ever-active-bounds = [6, 6]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 32, y = 27, rule = LifeHistory
19.A$2B6.A8.3A$3B6.A6.A14.B$4B3.3A6.2A12.2B$5B24.3B$6B22.4B$7B20.5B$
8B9.2A7.6B$9B8.2A6.7B$10B14.8B$32B$32B$32B$32B$32B$32B$32B$32B$32B$
32B$32B$32B$32B$32B$32B$32B$32B!
'''
