first-active-range = [37, 50]
active-window-range = [0, 20]

ever-active-bounds = [6, 6]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 28, y = 25, rule = LifeHistory
12.A.A$9.A2.2A.A2.2A$9.3A3.A3.A$12.A.A.3A6.A$9.2A.A.A.A6.3A$7.A2.A.A.
A.A5.A$7.2A2.2A.2A6.2A$6B$6B$15B$14B$14B2.2A$14B2.2A$14B$15B$16B$17B
9.2A$17B8.2A$17B10.A$17B$17B2.2A$17B2.2A$17B$17B$17B!
'''
