first-active-range = [37, 50]
active-window-range = [0, 20]

ever-active-bounds = [6, 6]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 32, y = 30, rule = LifeHistory
11.A.A$8.A2.2A.A2.2A$8.3A3.A3.A$11.A.A.3A6.A$8.2A.A.A.A6.3A$6.A2.A.A.
A.A5.A$6.2A2.2A.2A6.2A3$5.2A$5.A.A$7.A7.2A$7.2A6.2A$9.A$7.2A$7.A3.2A$
4.2A.A4.A3.4B5.2A$4.A2.A.3A3.6B3.2A$6.2A.A4.8B4.A$13.10B$12.12B$25B$
26B$27B$28B$29B$30B$31B$32B$32B!
'''
