first-active-range = [37, 50]
active-window-range = [0, 20]

ever-active-bounds = [7, 7]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 26, y = 29, rule = LifeHistory
19.A$17.3A$16.A$16.2A5$2.2A.2A3.2A$A2.A.2A3.2A$2A2$5.A2.A2.3B$5.4A2.
4B5.2A$2.A8.5B3.2A$2.5A3.7B4.A$6.A2.9B$4.A4.10B$4.2A2.12B$8.13B$7.15B
$7.16B$7.17B$7.18B$7.19B$7.19B$7.19B$7.19B$7.19B!
'''


