first-active-range = [37, 50]
active-window-range = [0, 20]

ever-active-bounds = [7, 7]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 27, y = 29, rule = LifeHistory
20.A$18.3A$17.A$17.2A3$6.A$5.A.A$5.A.A3.2A$6.A4.2A$2.2A$.A.A4.A$.A5.A
.A2.3B$2A4.A.2A2.4B5.2A$6.A5.5B3.2A$5.2A4.7B4.A$10.9B$8.12B$7.14B$7.
15B$7.16B$7.17B$7.18B$7.19B$7.20B$7.20B$7.20B$7.20B$7.20B!
'''
