first-active-range = [37, 50]
active-window-range = [0, 20]

ever-active-bounds = [7, 7]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 27, y = 33, rule = LifeHistory
17B$17B$17B$17B$17B$17B$17B7.A$17B5.3A$17B4.A$17B4.2A$17B$17B$14B$13B
$13B2.2A$13B2.2A$13B$14B$19B$20B5.2A$21B3.2A$22B4.A$23B$24B$25B$26B$
27B$27B$27B$27B$27B$27B$27B!
'''
