first-active-range = [35, 50]
active-window-range = [0, 20]

ever-active-bounds = [6, 6]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 32, y = 27, rule = LifeHistory
19.A$17.3A$16.A14.B$16.2A12.2B$29.3B$28.4B$27.5B$26.6B$25.7B$12.2A10.
8B$6.2A3.A.A9.9B$5.A.A4.A9.10B$5.A9.17B$4.2A3.23B$8.24B$8.12B2A10B$
20BABA9B$20BA11B$32B$32B$32B$32B$32B$32B$32B$32B$32B!
'''
