first-active-range = [18, 25]
active-window-range = [0, 18]
min-stable-interval = 3

max-active-cells = 17
ever-active-bounds = [7, 7]

stabilise-results = true

pattern-center = [15, 15]
pattern = '''
x = 26, y = 33, rule = LifeHistory
22.A$20.3A$19.A$19.2A2$6.2A2.A5.3A$6.A2.A.A3.A3.A$7.A.2A3.A5.A$8.A5.A
5.A$9.2A3.A5.A$10.A4.A3.A$8.A7.3A$8.2A2.2B$12.3B$20B2.2A$20B2.A$20B3.
3A$21B4.A$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B$22B
!
'''
