first-active-range = [12, 30]
active-window-range = [0, 18]
min-stable-interval = 3

max-active-cells = 17
ever-active-bounds = [7, 7]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 32, y = 33, rule = LifeHistory
22.A$20.3A$19.A$19.2A2$16.3A12.B$8.A6.A3.A10.2B$7.A.A4.A5.A8.3B$7.A.A
4.A5.A7.4B$8.A5.A5.A6.5B$4.2A9.A3.A3.9B$3.A.A4.A5.3A3.10B$3.A5.A.A9.
11B$2.2A4.A.2A8.12B$8.A6.17B$7.2A6.17B$15.17B$32B$32B$32B$32B$32B$32B
$32B$32B$32B$32B$32B$32B$32B$32B$32B$32B!
'''
