first-active-range = [15, 40]
active-window-range = [0, 18]
min-stable-interval = 3

max-active-cells = 17
ever-active-bounds = [7, 7]

stabilise-results = true

pattern-center = [15, 15]
pattern = '''
x = 23, y = 26, rule = LifeHistory
22B$22B$22B$22B$22B$21B$19B$18B4.A$17B3.3A$17B2.A$15B4.2A$14B$13B3.3A
$4B3.5B3.A3.A$3B5.4B2.A5.A$5.A8.A5.A$4.A.A7.A5.A$4.A.A8.A3.A$2.2A2.3A
7.3A$.A.A.A3.A$2.A2.A.2A.A$5.A2.A.A$6.2A2.2A7.2A$7.A.A9.A$7.A.A10.3A$
8.A13.A!
'''
