first-active-range = [3, 25]
active-window-range = [0, 18]
min-stable-interval = 3

max-active-cells = 17
ever-active-bounds = [7, 7]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 32, y = 33, rule = LifeHistory
13.A8.A$12.A.A5.3A$13.A5.A$9.2A8.2A$9.A$6.2A.A6.3A12.B$4.A2.A.2A4.A3.
A10.2B$4.2A.A6.A5.A8.3B$7.A6.A5.A7.4B$7.2A5.A5.A6.5B$15.A3.A3.9B$6B4.
3B3.3A3.10B$14B7.11B$15B5.12B$32B$32B$32B$32B$32B$32B$32B$32B$32B$32B
$32B$32B$32B$32B$32B$32B$32B$32B$32B!
'''
