first-active-range = [13, 29]
active-window-range = [0, 18]
min-stable-interval = 3

max-active-cells = 17
ever-active-bounds = [7, 7]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [16, 16]
pattern = '''
x = 32, y = 30, rule = LifeHistory
25B$25B$25B$25B$25B$24B$22B$21B4.A$20B3.3A$20B2.A8.A$18B4.2A5.3A$17B
11.A$16B3.3A6.2A$15B3.A3.A$15B2.A5.A$15B2.A5.A$10B7.A5.A$5B13.A3.A$4B
7.2A6.3A$6.2A2.A2.A$6.A4.A.A$3.2A.A5.A$4.A.A.2A14.A$3.A2.A2.A10.2A.A.
A$3.2A2.A4.A6.A.A.A.A$8.5A3.A2.A.A.A.2A$16.4A.2A2.A$10.2A.A6.A4.A.A$
10.A.2A4.A.A5.2A$18.2A!
'''
