first-active-range = [14, 40]
active-window-range = [0, 18]
min-stable-interval = 3

max-active-cells = 17
ever-active-bounds = [7, 7]

stabilise-results = true

pattern-center = [15, 15]
pattern = '''
x = 30, y = 30, rule = LifeHistory
27B$27B$27B$27B$27B$26B$24B$23B4.A$22B3.3A$22B2.A$20B4.2A$19B$18B3.3A
$17B3.A3.A$17B2.A5.A$17B2.A5.A$17B2.A5.A$17B3.A3.A$18B3.3A$19B$19B$
19B$19B7.A$17B5.2A.A.A$16B5.A.A.A.A$16B2.A2.A.A.A.2A$16B2.4A.2A2.A$
16B6.A4.A.A$17B3.A.A5.2A$17B3.2A!
'''
