first-active-range = [10, 70]
active-window-range = [0, 20]

ever-active-bounds = [6, 6]

stabilise-results = true

pattern-center = [15, 15]
pattern = '''
x = 32, y = 34, rule = LifeHistory
32B$32B$32B$32B$32B$32B$32B$32B$31B$30B$29B$3.25B$5.22B$.A5.19B$.3A3.
18B$4.A2.17B$3.A$3.2A9.3A$.2A10.A3.A$A2.4A5.A5.A$.A4.A5.A5.A$2A.2A7.A
5.A$A2.A9.A3.A$.A.A10.3A$2.A22.2A$17.A7.A.A$16.A.A8.A$17.A.A.2A4.2A$
15.A.A.A.A.A$14.A.A.A4.A$14.A.A2.4A$15.2A$21.2A$21.2A!
'''





