first-active-range = [5, 70]
active-window-range = [0, 20]

ever-active-bounds = [6, 6]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [16, 16]
pattern = '''
x = 32, y = 32, rule = LifeHistory
19B$19B$19B$19B$19B$19B$19B$19B$19B4.A$19B2.3A$19B.A$19B.2A$19B$19B$
14B$14B3.3A$14B2.A3.A$14B.A5.A$14B.A5.A$14B.A5.A$14B2.A3.A$14B3.3A$
14B14.2A$15B5.A7.A.A$15B4.A.A8.A$15B5.A.A.2A4.2A$15B3.A.A.A.A.A$15B2.
A.A.A4.A$15B2.A.A2.4A$15B3.2A$24.2A$24.2A!
'''
