first-active-range = [5, 70]
active-window-range = [0, 20]

ever-active-bounds = [6, 6]

stabilise-results = true
skip-glancing = true
forbid-eater2 = true

pattern-center = [15, 15]
pattern = '''
x = 29, y = 32, rule = LifeHistory
29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$29B$11B$11B3.3A$
11B2.A3.A$11B.A5.A$12.A5.A$12.A5.A$7.2A4.A3.A$6.A.A5.3A$6.A18.2A$5.2A
10.A7.A.A$16.A.A8.A$17.A.A.2A4.2A$15.A.A.A.A.A$14.A.A.A4.A$14.A.A2.4A
$15.2A$21.2A$21.2A!
'''
